### ISSUE TITLE
How to add access token for viewing results?

### ISSUE THREAD

**Issue by nk-dev0** [developmentseed/skynet-train#23]
This is just what I was looking for thanks, but is there a way to input the mapbox access token so users can view the original input image? When I click the 'view results' link, I can view the osm annotation and prediction images, but it's not too helpful without being able to see what type of input image it is. Thanks.

**Comment by anandthakker** [comment]
@nkrall I believe Mapbox still has free accounts (https://mapbox.com) -- if you sign up for one, you can use your token and it should work
