### ISSUE TITLE
Attempt to download .caffemodel from S3: Forbidden

### ISSUE THREAD

**Issue by nk-dev0** [developmentseed/skynet-train#24]
After configuring my AWS account with access key + secret access key + region + output type, I ran: 

`aws s3 --no-verify-ssl cp s3://skynet-models/segnet-ts12-1/manifest.txt .`

Which returned error:
```
A client error (403) occurred when calling the HeadObject operation: Forbidden

Completed 1 part(s) with ... file(s) remaining
```
Is there some piece to allow it to be accessed?

**Comment by anandthakker** [comment]
@nkrall my guess is that because it's a requester pays bucket, you may need to use the `aws s3api` (instead of the more convenient `aws s3`) command.  Something like:

```
aws s3api get-object --bucket skynet-models --key manifest.txt --request-payer requester manifest.txt
```

**Comment by nk-dev0** [comment]
That works great, thanks.
