### ISSUE TITLE
how to run docker

### ISSUE THREAD

**Issue by oneOfThePeople** [developmentseed/skynet-train#38]
I try to run spacenet example and i use [this](https://github.com/developmentseed/spacenet-data) instruction to create the data
but the skynet-train docker dont have access to the data in spacenet-data docker and even if it had 
the paths in train.txt  are not realy exist 
like -"/spacenet/processedData/3band/3band_013022232022_Public_img6005.tif /data/labels/grayscale/013022232022_Public_img6005.tif"
so what i need to change for succeed to run the skynet-train docker?
thank you

**Comment by oneOfThePeople** [comment]
i fix this by use this command line:
`nvidia-docker run -v /mnt/AOI_1_Rio:/spacenet -v /mnt/spacenet-1:/data -v /mnt/output:/output developmentseed/skynet-train:gpu`
my problem now is that not all of the image are in the same size...
how you deal with this?

**Comment by drewbo** [comment]
Hi @oneOfThePeople, thanks for the feedback. We've had some problems doing path replacement in the `train.txt` and `val.txt` files as well. We updated `skynet-data` to [improve this process](https://github.com/developmentseed/skynet-data/issues/8) and I run a `sed` script if I mess up anything beyond that. Happy to check out any ideas you have for improving that bit though!

For different image sizes, we've been using tile servers and 256x256 pngs/jpg for the most part so we haven't run into this yet. You will likely have to crop or somehow standardize them for the model to succeed.

**Comment by oneOfThePeople** [comment]
thank you
