### ISSUE TITLE
Branch:script-training:how to use segnet/demo examples

### ISSUE THREAD

**Issue by yili9111** [developmentseed/skynet-train#51]
I am using Branch:script-training, I want  to see  demo result in Browser,  My operation  as follows ：
(1)start the predect server:
 python segnet/demo.py --model model/segnet_deploy.prototxt --weights del/test_weights.caffemodel  --classes model/classes.json
success ~
(2)start webserver 
npm run bundle-demo
npm run bundle-viewer
test1:
node segnet/demo.js
error: 
exports.easeCubicInOut = function(t: number): number ...
test2:
node segnet/static/demo.js 
error: module.exports = self;ReferenceError: self is not defined..

can you  tell me what should I do ? can you describe more info about this demo?

**Comment by drewbo** [comment]
@yili9111 this demo can be run by serving the built static files, (e.g. `python -m http.server`) but can't be run directly. The demo is for creating a tile server which predicts on the fly and requires a trained model/weights to begin: 
![ml-tile-server](https://user-images.githubusercontent.com/7108211/41300392-98ced082-6e33-11e8-98a4-67e8c4c877de.gif)

**Comment by yili9111** [comment]
prefect ~ successful, thank you very much ~
