### ISSUE TITLE
Release of trained caffemodel?

### ISSUE THREAD

**Issue by nk-dev0** [developmentseed/skynet-train#7]
I'm looking to use this as a pretraining step for fine-tuning later on. Would it be possible to have the pre-trained caffemodel that you've created? 

I'm working on a similar task, and I believe transferring weights from ImageNet or Pascal for example to this overhead imagery case may be problematic in more difficult situations. So using a pretrained network in the correct domain of overhead imagery would improve performance significantly I believe. Thanks.

**Comment by anandthakker** [comment]
@nkrall Yes, this is definitely something I've been wanting to do, just swamped in other projects.  Let me see if I can make it happen this week.

**Comment by nk-dev0** [comment]
@anandthakker Awesome thank you!

**Comment by nk-dev0** [comment]
@anandthakker Hey not to bother too much but I'm just checking if there are any updates on this

**Comment by anandthakker** [comment]
Quick update: currently in progress working on on #9 -- after that is done (which I believe will happen this week), this will be next and should be quick.

**Comment by anandthakker** [comment]
@nkrall see #22 !
